SELECT 'Oracle 11g R2', LENGTH('Oracle 11g R2'), LENGTHB('Oracle 11g R2')
FROM DUAL;

SELECT '오라클 11g R2', LENGTH('오라클 11g R2'), LENGTHB('오라클 11g R2')
FROM DUAL;

SELECT '11g R2', LENGTH('11g R2'), LENGTHB('11g R2')
FROM DUAL;


SELECT '오라클', LENGTH('오라클'), LENGTHB('오라클')
FROM DUAL;

--1. 53쪽 실습
CREATE TABLE EX2_2 (
    COL1 VARCHAR2(3), --3바이트. NULL 허용하면 굳이 안써도 된다
    COL2 VARCHAR2(3 BYTE),
    COL3 VARCHAR2(3 CHAR)
);

--확인하기
SELECT *
FROM USER_TABLES;

SELECT TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, NULLABLE
FROM USER_TAB_COLUMNS
WHERE TABLE_NAME='EX2_2';

--삽입하기
INSERT INTO EX2_2(COL1, COL2, COL3)
VALUES('ABC', 'ABC', 'AC');

SELECT *
FROM EX2_2;

COMMIT;
--LENGTH나 LENGTHB나 결과 같다
SELECT LENGTHB(COL1), LENGTHB(COL2), LENGTHB(COL3)
FROM EX2_2;
--COL1, COL2 데이터 크기가 작아 안되는것인데 값에 NULL값을 넣어보면 됨
INSERT INTO EX2_2(COL1, COL2, COL3)
VALUES( NULL, NULL, '이순신');

INSERT INTO EX2_2(COL3)
VALUES('고희동');

SELECT *
FROM EX2_2;

COMMIT;

SELECT COL3, LENGTH(COL3), LENGTHB(COL3)
FROM EX2_2;

--P55 NUMBER 관련 실습
SELECT 30.5, CEIL(30.524), FLOOR(30.524), 
            ROUND(30.524), 
            ROUND(30.524, 0), --0.5가 5보다 큼
            ROUND(30.524, 1), --0.02가 5보다 작다
            ROUND(30.524, 2), --0.004가 5보다 작다
            ROUND(30.524, -1), -- 1의자리 반올림
            ROUND(30.524, -2) --10의자리 반올림
FROM DUAL;

--제약조건 연습하기 P60
CREATE TABLE EX2_6(
    COL1 VARCHAR2(10), 
    COL2 VARCHAR2(10) NOT NULL
);

--COL2가 NOT NULL이라 삽입실패
INSERT INTO EX2_6(COL1, COL2)
VALUES(NULL, NULL);
--''은 공백문자열. NULL데이터로 취급한다.
INSERT INTO EX2_6(COL1, COL2)
VALUES(NULL, '');
--''에 스페이스 침. 스페이스도 문자데이터.
INSERT INTO EX2_6(COL1, COL2)
VALUES(NULL, ' ');

--제약조건확인하기
SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE, SEARCH_CONDITION
FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'EX2_6';

--2_6_1 생성
CREATE TABLE EX2_6_1(
    COL1 CHAR(1), 
    COL2 VARCHAR2(10) NOT NULL,
    CONSTRAINT ck_ex2_6_1_col1 CHECK (col1 in ('M', 'F'))
);
--2_6_1에 파일 넣기
INSERT INTO EX2_6_1(COL1, COL2)
VALUES('M', 'ABC');

SELECT * FROM EX2_6_1;

INSERT INTO EX2_6_1(COL1, COL2)
VALUES('F', 'AAAAA');
--Z는 안되는게 맞아 M F 만 된다
INSERT INTO EX2_6_1(COL1, COL2)
VALUES('Z', 'ABC');

--COLUMN_CLOSE 써보기
ALTER TABLE EX2_6_1
    ADD (COL3 VARCHAR2(5 CHAR));
SELECT *
FROM USER_TAB_COLUMNS
WHERE TABLE_NAME = 'EX2_6_1';

ALTER TABLE EX2_6_1
    ADD CONSTRAINT ck_ex2_6_1_col3 CHECK (col3 IN ('결제완료', '상품준비중', '배송준비중', '배송중', '배송완료', '구매완료'));
    
INSERT INTO EX2_6_1 
VALUES(NULL, 'GREETINGS', NULL);
--COL1, COL3 은 생략가능이라 NULL 넣음
INSERT INTO EX2_6_1 (COL1, COL2, COL3)
VALUES(NULL, 'GREETINGS1', NULL);
--COL2만 NOT NULL이니까 생략불가. 따로 넣어본다. COL1, COL3 은 생략가능이라 굳이 안써도 된다.
INSERT INTO EX2_6_1 (COL2)
VALUES('GREETINGS2');

INSERT INTO EX2_6_1 (COL1, COL2, COL3)
VALUES('M', 'GREETINGS3', '상품준비중');

SELECT *
FROM EX2_6_1;

--상품준비중을 배송준비중으로 바꿔
UPDATE EX2_6_1
SET COL3 = '배송준비중'
WHERE COL3 = '상품준비중';
--결과 확인하기
SELECT *
FROM EX2_6_1;
--배송준비중을 배송중으로 바꾸기
UPDATE EX2_6_1
SET COL3 = '배송중'
WHERE COL3 = '배송준비중';

--퀴즈 delivery 테이블..dno(배송번호), status(내용: R ready, M moving, C completed, ddatetime 3개 컬럼.
--dno 100-R-'2017/07/27 15:10:37'   100-M-'2017/07/27 17:00:02'      100-C-'2017/07/27 '19:30:35'
--순서: 1. 테이블 생성하기
create table T_DELIVERY (
    DNO NUMBER (3) NOT NULL,
    STATUS CHAR(1) NOT NULL,
    DDATETIME DATE);
--2. PK 생성하기(PK 자체가 UNIQUE INDEX 만들어서 굳이 유니크 따로 만들필요 없다
ALTER TABLE T_DELIVERY
    ADD CONSTRAINT PK_T_DELIVERY PRIMARY KEY(DNO, STATUS);
--3 제약조건 설정하기(R, M, C) CK:CHECK CONSTRAINT
ALTER TABLE T_DELIVERY 
ADD CONSTRAINT CK_T_DELIVERY_STATUS CHECK(STATUS IN ('R', 'M', 'C'));

--4 테이블에 R M C 순으로 데이터 생성하기(날짜 상관없대)
INSERT INTO T_DELIVERY (DNO, STATUS, DDATETIME)
VALUES(100, 'R', SYSDATE);
INSERT INTO T_DELIVERY (DNO, STATUS, DDATETIME)
VALUES(100, 'M', SYSDATE);
INSERT INTO T_DELIVERY (DNO, STATUS, DDATETIME)
VALUES(100, 'C', SYSDATE);

SELECT DNO, STATUS, TO_CHAR(DDATETIME, 'YYYY-MM-DD HH24:MI:SS')
FROM T_DELIVERY;
--커밋하기
COMMIT;

SELECT *
FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'T_DELIVERY';

--T_DSTATUS 테이블 만들고 아래에 CODE 컬럼(PK), TITLE 컬럼. 'R'-'READY', 'M'-'MOVING', 'C'-'COMPLETED'
--원래 표의 STATUS가 FK가 된다. 만들때 ALTER TABLE 참조하는 ADD CONSTRAINT FK_T_DELIVERY(컬럼명) REFERENCES 참조되는 테이블명(컬럼명)

--1. T_DSTATUS 생성 
CREATE TABLE T_DSTATUS (
   CODE CHAR(1) NOT NULL,
   TITLE VARCHAR2(9) NOT NULL
   );  --CREATE에서만 NOT NULL을 넣을 수 있다.
--2. 데이터넣기 후에 커밋해야한다고
INSERT INTO T_DSTATUS(CODE, TITLE)
VALUES ('R', 'READY');
INSERT INTO T_DSTATUS(CODE, TITLE)
VALUES ('M', 'MOVING');
INSERT INTO T_DSTATUS(CODE, TITLE)
VALUES ('C', 'COMPLETED');
SELECT * FROM T_DSTATUS;
COMMIT;
--3. PK만들기 
ALTER TABLE T_DSTATUS
    ADD CONSTRAINT PK_T_DSTATUS PRIMARY KEY(CODE);
--그리고 FK 만들기    
ALTER TABLE T_DELIVERY
    ADD CONSTRAINT FK_T_DELIVERY_STATUS FOREIGN KEY (STATUS)
    REFERENCES T_DSTATUS (CODE); 
--4. 확인
SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME='T_DSTATUS';
SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME='T_DELIVERY';

--퀴즈 또. 조회결과에 R->READY  M->MOVING  C->COMPLETED T_DSTATUS의 타이틀을 최신순으로 출력해서 결과를 보여준다. 
SELECT a.DNO, b.TITLE, TO_CHAR(DDATETIME, 'YYYY-MM-DD HH24:MI:SS') "DTIME"
FROM T_DELIVERY a JOIN T_DSTATUS b ON (a.STATUS = b.CODE)
ORDER BY DDATETIME DESC;

--NOT NULL 테스트
CREATE TABLE EX_NN_TEST(
    COL1 NUMBER(3) NOT NULL, COL2 VARCHAR2(10), COL3 DATE DEFAULT SYSDATE   --INSERT SYSDATE 필요없게해주는 디폴트
);
INSERT INTO EX_NN_TEST(COL1, COL2)
VALUES(100, 'TEST');

SELECT * FROM EX_NN_TEST;

ALTER TABLE EX_NN_TEST
    MODIFY COL2 VARCHAR2(20);  --CREATE에서 못하면 ALTER에서 MODIFY로 바꾸자
SELECT COLUMN_NAME, DATA_TYPE, DATA_LENGTH, NULLABLE, DATA_DEFAULT FROM USER_TAB_COLUMNS WHERE TABLE_NAME='EX_NN_TEST';