DROP TABLE T_RECEIPT_DETAIL PURGE;
DROP TABLE T_RECEIPT PURGE;
DROP TABLE T_MENU PURGE;

--T_MENU 테이블 생성
CREATE TABLE T_MENU
(
	MENU_NUM             NUMBER(3) NOT NULL ,
	TITLE                VARCHAR2(50) NULL ,
	PRICE                NUMBER(7) NULL 
);

--MENU_NUM에 대해서 유니크인덱스 생성
CREATE UNIQUE INDEX XPKT_MENU ON T_MENU
(MENU_NUM   ASC);

--T_MENU 테이블에 PK 정보를 추가
ALTER TABLE T_MENU
	ADD CONSTRAINT  XPKT_MENU PRIMARY KEY (MENU_NUM);

--T_RECEIPT 테이블 생성
CREATE TABLE T_RECEIPT
(
	RECEIPT_NUM          NUMBER(3) NOT NULL ,
	RECEIPT_DATETIME     DATE NULL 
);

--RECEIPT_NUM에 대해서 유니크인덱스 생성
CREATE UNIQUE INDEX XPKT_RECEIPT ON T_RECEIPT
(RECEIPT_NUM   ASC);

--T_RECEIPT 테이블에 PK를 추가
ALTER TABLE T_RECEIPT
	ADD CONSTRAINT  XPKT_RECEIPT PRIMARY KEY (RECEIPT_NUM);

--T_RECEIPT_DETAIL 테이블 생성
CREATE TABLE T_RECEIPT_DETAIL
(
	QTY                  NUMBER(2) NULL ,
	MENU_NUM             NUMBER(3) NOT NULL ,
	RECEIPT_NUM          NUMBER(3) NOT NULL 
);

--T_RECEIPT_DETAIL 테이블에 RECEIPT_NUM과 MENU_NUM에 대해서 유니크 인덱스 생성
CREATE UNIQUE INDEX XPKT_RECEIPT_DETAIL ON T_RECEIPT_DETAIL
(RECEIPT_NUM   ASC,MENU_NUM   ASC);

--T_RECEIPT_DETAIL 테이블에 두 개의 컬럼(RECEIPT_NUM,MENU_NUM)에 대해서 PK 설정
ALTER TABLE T_RECEIPT_DETAIL
	ADD CONSTRAINT  XPKT_RECEIPT_DETAIL PRIMARY KEY (RECEIPT_NUM,MENU_NUM);
    
--FK_T_RECEIPT_DETAIL_MENU_NUM FK를 제거한다
ALTER TABLE T_RECEIPT_DETAIL
    DROP CONSTRAINT FK_T_RECEIPT_DETAIL_MENU_NUM;
    
--T_RECEIPT_DETAIL 변경하는데 디테일의 MENU_NUM이 T_MENU의 MENU_NUM을 참조한다는 FK를 추가한다
ALTER TABLE T_RECEIPT_DETAIL
	ADD (CONSTRAINT FK_T_RECEIPT_DETAIL_MENU_NUM FOREIGN KEY (MENU_NUM) REFERENCES T_MENU (MENU_NUM));
    
--FK_T_RECEIPT_DETAIL_REC_NUM를 제거한다
 ALTER TABLE T_RECEIPT_DETAIL
    DROP CONSTRAINT FK_T_RECEIPT_DETAIL_REC_NUM;
--T_RECEIPT_DETAIL 변경하는데 디테일의 RECEIPT_NUM이 T_RECEIPT의 RECEIPT_NUM을 참조한다는 FK를 추가한다
ALTER TABLE T_RECEIPT_DETAIL
	ADD (CONSTRAINT FK_T_RECEIPT_DETAIL_REC_NUM FOREIGN KEY (RECEIPT_NUM) REFERENCES T_RECEIPT (RECEIPT_NUM));
    
